# Generated by Django 5.2 on 2025-05-10 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.TextField()),
                ('pricing', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNo', models.CharField(max_length=10)),
                ('password', models.CharField(default='', max_length=128)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNo', models.CharField(max_length=10)),
                ('password', models.CharField(default='', max_length=128)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('booking_price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppms_app.customer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppms_app.venue')),
            ],
        ),
    ]
